version:  '3'

services:
   
    client:
        tty: true
        build: ./client
        environment:
            - REACT_APP_PORT=${REACT_APP_PORT}
     
        expose: 
            - ${REACT_APP_PORT}
        ports: 
            - ${REACT_APP_PORT}:${REACT_APP_PORT}
        volumes:
            - /app/node_modules
            - ./client:/app
        command: npm start