version: '3'
services: 
    nginx:
            restart: always
            build: 
                 context: ./nginx
            ports: 
                  - '3050:80'
    api: 
         build: 
             context: ./server
         volumes:
              - /app/node_modules
              - ./server:/app
    client: 
           build: 
                context: ./client
           volumes:
                - /app/node_modules
                - ./client:/app